project:
  type: website
  output-dir: docs

website:
  title: "doho1 blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://gist.github.com/dohohyeon

format:
  html:
    theme:
      - ludx
      - brand
    css: styles.css



